# Конфигурационные данные, используемые во всём приложении

# Словарь значений по умолчанию для всех переменных шаблона
DEFAULTS = {
    "drug_name": "Дабигатрана этексилат",
    "dose_mg": "150",
    "protocol_id": "PROT-2024-001",
    "sponsor_name": "ООО 'НТФФ 'ПОЛИСАН'",
    "study_center": "Клинический центр",
    "bioanalytical_lab_name": "Лаборатория биоаналитики",
    "active_substance": "дабигатрана этексилат",
    "reference_product_name": "Прадакса®",
    "ru_number": "ЛП-№123456",
    "intake_time": "натощак",
    "dosing_regimen_ru": "однократно",
    "study_design": "открытое рандомизированное двухпериодное перекрестное",
    "washout_days": "7",
    "sampling_type": "по 34 образца в каждом периоде",
    "screening_duration_days": "14",
    "pk_period_duration_days": "4",
    "follow_up_duration_days": "7",
    "period2_dosing_day": "14",
    "fasting_hours": "8",
    "water_volume_ml": "200",
    "center_stay_hours": "48",
    "period2_dosing_day+n": "16",
    "blood_samples_count": "18",
    "sample_volume_ml": "5",
    "samples_per_period": "18",
    "volume_sample": "180",
    "volume_sample_per_period": "90",
    "sample_size": "68",
    "washout_period": "7 дней",
    "pre_dosing_minutes": "30",
    "post_dosing_minutes": "20,40,60,80,100,120,140,160,180,210,240,300,360,480,600,720,1440,2880",
    "post_dosing_hours": "1,2,3,4,6,8,10,12,16,24,48",
    "half_life_hours": "12",
    "cv_intra_value": "23.5",
    "pk_cmax": "57.49",
    "pk_auc0": "1407.1",
    "dropout_rate": "15",
    "total_enrolled": "68",
    "screening_failure_rate": "20",
    "total_screened": "85",
    "gender_allowed": "мужчины и женщины",
    "min_weight_female_kg": "45",
    "female_reproductive_risk_status": "включены",
    "age_max": "45",
    "alcohol_abstinence_hours": "72",
    "contraception_methods": "презерватив со спермицидом, диафрагма, внутриматочная спираль",
    "prior_study_exclusion_months": "3",
    "trade_name_ref": "Прадакса®",
    "inn_ref": "дабигатрана этексилат",
    "dosage_form": "капсулы",
    "period2_end": "17",
    "ci_limits": "80.00-125.00",
    "document_type_ru": "Протокол",
    "protocol_version_number": "1.0",
    "protocol_version_date": "2025-03-20",
    "insurance_company_name": "СК 'Согласие'",
    "manufacturer": "ООО 'НТФФ 'ПОЛИСАН', Россия",
    "manufacturer_ref": "Берингер Ингельхайм Интернешнл ГмбХ, Германия",
    "dosage_form_ref": "капсулы",
    "dosage_ref": "150 мг",
    "active_substance_ref": "дабигатрана этексилат",
    "auxiliary_substances_ref": "гипролоза, кремния диоксид коллоидный, тальк",
    "storage_conditions_ref": "хранить при температуре не выше 25 °C",
    "auxiliary_substances": "гипролоза, кремния диоксид коллоидный, тальк",
    "auxiliary_substances_amount": "достаточное количество",
    "active_substance_amount": "150 мг",
    "dosage": "150 мг",
    "storage_conditions": "хранить при температуре не выше 25 °C",
    "be_lower_limit": "80.00",
    "be_upper_limit": "125.00",
    "gmr": "0.95",
    "ci_lower": "90.12",
    "ci_upper": "112.45",
    "primary_pk_param": "Cmax/AUC",
    "study_condition": "натощак",
    "design_type": "перекрестный",
}

# URL внешнего ИИ-сервиса (заменить на реальный)
AI_SERVICE_URL = "http://ai-service:8001"